### ISSUE TITLE
[v. 4.1.0] Crash when opening chat

### ISSUE THREAD

**Issue by Deepscorn** [helpshift/helpshift-unity-examples#1]
I know it's NOT about the version provided here (at the time of creating issue it is 4.0.1), but I don't know where to report issue - didn't find any way.

Crash when opening chat:

```
Caused by: java.lang.NoSuchFieldError: No field colorAccent of type I in class Lcom/helpshift/R$attr; or its superclasses (declaration of 'com.helpshift.R$attr' appears in /data/app/our.package.name-2/base.apk)
        at com.helpshift.support.conversations.ConversationFragment.initialize(ConversationFragment.java:162)
        at com.helpshift.support.conversations.ConversationFragment.onViewCreated(ConversationFragment.java:113)
        at com.helpshift.support.conversations.ConversationalFragment.onViewCreated(ConversationalFragment.java:47)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
```
I found the line where it happens, ConversationFragment.java:
import com.helpshift.R.attr;
<...>
Styles.setDrawable(getContext(), localView4, R.drawable.hs__circle, R.attr.colorAccent);

R is com.helpshift.R (as you see in import).
I know that using R.attr.colorAccent is the way you can get colorAccent specific to app programmatically (https://stackoverflow.com/questions/27611173/how-to-get-accent-color-programmatically)

I looked into our apk and found out that in com.helpshift.R.java:
hs__circle - exists:
```
    public static final int hs__circle = 2131165369;
```
colorAccent - does not exist
and looking into our.package.name.R.java:
colorAccent - exists:
```
    public static final int colorAccent = 2130903134;
```

So, looks to me, that it is programming error - R.attr.colorAccent should be called on application package, not com.helpshift...

**Comment by DeepanshuDialani** [comment]
@Deepscorn 
Thanks for reporting this issue. Can you please contact us via our support channels by emailing to support@helpshift.com for efficient resolution. 

Also, please send in the following details about the integration:
1. What is the build system that you're building the app with? "gradle", "in-built" or "export to android studio"?
2. What is the Unity version that you are using?
3. Are you using Helpshift-only Dex or Unified Dex SDK package from https://developers.helpshift.com/unity/getting-started-android/#hs-only-dex-unity?
4. How are you adding the support library dependencies? Through custom build.gradle or manually adding the library .aar files? Incase of the latter, what all support libraries have you added?

**Comment by Deepscorn** [comment]
Hello! Thank you. I fixed my issue with generating Helpshift.aar with https://github.com/helpshift/dexter/tree/master/PluginToAAR as suggested here https://developers.helpshift.com/unity/troubleshooting-android/#fix-inbuilt-gradle-build
1. gradle
2. unity 2018.1.9f1
3. Helpshift SDK-only dex unity package
4. Through https://github.com/googlesamples/unity-jar-resolver, then after resolve Plugins/Android is populated with aar, so I can run your PluginToAAR script
